//
//  SeriesRoundPlannedTeeGroupRenumberTests.swift
//  HackersUnitTests
//

@testable import Hackers
import XCTest

final class SeriesRoundPlannedTeeGroupRenumberTests: XCTestCase {

    func testRenumberPreservesArrayOrderAfterSwap() {
        let seatA = SeriesRoundPlannedSeat(id: "sa", memberID: "mA", teeOrder: 1, source: .autoGenerated)
        let seatB = SeriesRoundPlannedSeat(id: "sb", memberID: "mB", teeOrder: 2, source: .autoGenerated)
        var group = SeriesRoundPlannedTeeGroup(
            id: "g1",
            index: 0,
            startingHole: 1,
            seats: [seatA, seatB],
            source: .autoGenerated
        )
        group.seats.swapAt(0, 1)
        let out = group.renumberedPreservingSeatOrder()
        XCTAssertEqual(out.seats.count, 2)
        XCTAssertEqual(out.seats[0].memberID, "mB")
        XCTAssertEqual(out.seats[0].teeOrder, 1)
        XCTAssertEqual(out.seats[1].memberID, "mA")
        XCTAssertEqual(out.seats[1].teeOrder, 2)
    }
}
